language: ruby
rvm:
- 2.1.3

addons:
  code_climate:
    repo_token: 1c5d8ac845edfb9818032b4a6af65ca0f6cd04674f0c2527712d140f53426377

deploy:
  provider: heroku
  app: workdat
  buildpack: ruby
  strategy: api
  api_key:
    secure: Fh0zpjTMA3UmtzuYBBNQ/52Fl6Lha8PKv4ViG1pSaEg8Lsr1zMCT7e6B1rWP0P8HaL2Y8QKMNA705tiWc2ehra0rQq07Kf1iv/kgFfj2Vob3NKtN/1ZJARGP0KbC4gt/SMA8X/BNfcdfKgAqIwSDZ3obBuwGAiw03AMguVOaVVM=
